// Basic Arithmetic Operations in JavaScript
let a = 10;
let b = 20;
let sum = a + b;
console.log("Sum:", sum);
let multiply = a * b;
console.log("Multiply:", multiply);
let divide = b / a;
console.log("Divide:", divide);let subtract = b - a;
console.log("Subtract:", subtract);
let modulus = b % a;
console.log("Modulus:", modulus);
let exponent = a ** 2;
console.log("Exponent:", exponent);
let increment = ++a;
console.log("Increment:", increment);
let decrement = --b;
console.log("Decrement:", decrement);
let floorDivision = Math.floor(b / a);
console.log("Floor Division:", floorDivision);
let randomNum = Math.random() * 100;
console.log("Random Number:", randomNum);
let absValue = Math.abs(-a);
console.log("Absolute Value:", absValue);
let sqrtValue = Math.sqrt(b);
console.log("Square Root:", sqrtValue);
let roundValue = Math.round(4.7);
console.log("Round Value:", roundValue);
let ceilValue = Math.ceil(4.2);
console.log("Ceil Value:", ceilValue);
let floorValue = Math.floor(4.7);
console.log("Floor Value:", floorValue);
let minValue = Math.min(a, b, 5, 15);
console.log("Min Value:", minValue);
let maxValue = Math.max(a, b, 5, 15);
console.log("Max Value:", maxValue);